# Generated by Django 5.2.1 on 2025-06-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_name',
            new_name='status',
        ),
    ]
